# Generated by Django 5.2.8 on 2025-11-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saepapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='estoque_minimo',
            field=models.IntegerField(default=0),
        ),
    ]
