# Generated by Django 5.2.8 on 2025-11-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saepapp', '0002_ferramenta_estoque_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='quantidade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
